<?xml version="1.0"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" modelName="C:\Users\Elena D\Desktop\openHAB_simple_test.acs_2023_3_27_11_57" version="webACS_v0.1_to_be_replaced_by_proper_version_number">
  <modelDescription>
    <shortDescription />
    <requirements />
    <description />
  </modelDescription>
  <components>
    <component id="openHAB.1_c" type_id="asterics.openHAB">
      <description>OpenHAB Binding - Interfacing to the openHAB home automation suite</description>
      <ports>
        <inputPort portTypeID="item1in" sync="false">
          <properties />
        </inputPort>
        <inputPort portTypeID="item2in" sync="false">
          <properties />
        </inputPort>
        <inputPort portTypeID="item3in" sync="false">
          <properties />
        </inputPort>
        <inputPort portTypeID="item4in" sync="false">
          <properties />
        </inputPort>
        <inputPort portTypeID="item5in" sync="false">
          <properties />
        </inputPort>
        <inputPort portTypeID="item6in" sync="false">
          <properties />
        </inputPort>
        <inputPort portTypeID="actionString" sync="false">
          <properties />
        </inputPort>
        <outputPort portTypeID="item1">
          <properties />
        </outputPort>
        <outputPort portTypeID="item2">
          <properties />
        </outputPort>
        <outputPort portTypeID="item3">
          <properties />
        </outputPort>
        <outputPort portTypeID="item4">
          <properties />
        </outputPort>
        <outputPort portTypeID="item5">
          <properties />
        </outputPort>
        <outputPort portTypeID="item6">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="updaterate" value="1000" />
        <property name="hostname" value="openhabian" />
        <property name="port" value="8080" />
        <property name="protocol" value="0" />
        <property name="lazyCertificates" value="false" />
        <property name="username" value="" />
        <property name="password" value="" />
        <property name="item1in" value="Temperature_GF_Kitchen" />
        <property name="item2in" value="" />
        <property name="item3in" value="" />
        <property name="item4in" value="" />
        <property name="item5in" value="" />
        <property name="item6in" value="" />
        <property name="item1out" value="Temperature_GF_Kitchen" />
        <property name="item2out" value="Light_GF_Kitchen_Ceiling" />
        <property name="item3out" value="Shutter_GF_Kitchen" />
        <property name="item4out" value="" />
        <property name="item5out" value="" />
        <property name="item6out" value="" />
        <property name="item1event" value="Temperature_GF_Kitchen" />
        <property name="item2event" value="Light_GF_Kitchen_Ceiling" />
        <property name="item3event" value="Shutter_GF_Kitchen" />
        <property name="item4event" value="" />
        <property name="item5event" value="" />
        <property name="item6event" value="" />
      </properties>
      <layout>
        <posX>228</posX>
        <posY>6</posY>
      </layout>
    </component>
    <component id="ButtonGrid.1" type_id="asterics.ButtonGrid">
      <description>Keyboard which sends event after button press</description>
      <ports />
      <properties>
        <property name="caption" value="Keyboard" />
        <property name="horizontalOrientation" value="false" />
        <property name="textColor" value="13" />
        <property name="backgroundColor" value="13" />
        <property name="borderColor" value="13" />
        <property name="borderThickness" value="2" />
        <property name="selectionFrameColor" value="13" />
        <property name="selectionFrameThickness" value="4" />
        <property name="displayGUI" value="true" />
        <property name="buttonCaption1" value="Item Light_GF_Kitchen_Ceiling ON" />
        <property name="buttonCaption2" value="Item Light_GF_Kitchen_Ceiling OFF" />
        <property name="buttonCaption3" value="Item Shutter_GF_Kitchen Up" />
        <property name="buttonCaption4" value="Item Shutter_GF_Kitchen Down" />
        <property name="buttonCaption5" value="" />
        <property name="buttonCaption6" value="" />
        <property name="buttonCaption7" value="" />
        <property name="buttonCaption8" value="" />
        <property name="buttonCaption9" value="" />
        <property name="buttonCaption10" value="" />
        <property name="buttonCaption11" value="" />
        <property name="buttonCaption12" value="" />
        <property name="buttonCaption13" value="" />
        <property name="buttonCaption14" value="" />
        <property name="buttonCaption15" value="" />
        <property name="buttonCaption16" value="" />
        <property name="buttonCaption17" value="" />
        <property name="buttonCaption18" value="" />
        <property name="buttonCaption19" value="" />
        <property name="buttonCaption20" value="" />
        <property name="toolTip1" value="" />
        <property name="toolTip2" value="" />
        <property name="toolTip3" value="" />
        <property name="toolTip4" value="" />
        <property name="toolTip5" value="" />
        <property name="toolTip6" value="" />
        <property name="toolTip7" value="" />
        <property name="toolTip8" value="" />
        <property name="toolTip9" value="" />
        <property name="toolTip10" value="" />
        <property name="toolTip11" value="" />
        <property name="toolTip12" value="" />
        <property name="toolTip13" value="" />
        <property name="toolTip14" value="" />
        <property name="toolTip15" value="" />
        <property name="toolTip16" value="" />
        <property name="toolTip17" value="" />
        <property name="toolTip18" value="" />
        <property name="toolTip19" value="" />
        <property name="toolTip20" value="" />
      </properties>
      <layout>
        <posX>339</posX>
        <posY>47</posY>
      </layout>
      <gui>
        <posX>50</posX>
        <posY>1615</posY>
        <width>2604</width>
        <height>1666</height>
      </gui>
    </component>
    <component id="StringDispatcher.1" type_id="asterics.StringDispatcher">
      <description>Send text from chosen slot</description>
      <ports>
        <inputPort portTypeID="slotDispatch" sync="false">
          <properties />
        </inputPort>
        <outputPort portTypeID="output">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="delay" value="300" />
        <property name="slot1" value="Light_GF_Kitchen_Ceiling,ON" />
        <property name="slot2" value="Light_GF_Kitchen_Ceiling,OFF" />
        <property name="slot3" value="Shutter_GF_Kitchen,UP" />
        <property name="slot4" value="Shutter_GF_Kitchen,DOWN" />
        <property name="slot5" value="" />
        <property name="slot6" value="" />
        <property name="slot7" value="" />
        <property name="slot8" value="" />
        <property name="slot9" value="" />
        <property name="slot10" value="" />
        <property name="slot11" value="" />
        <property name="slot12" value="" />
        <property name="slot13" value="" />
        <property name="slot14" value="" />
        <property name="slot15" value="" />
        <property name="slot16" value="" />
        <property name="slot17" value="" />
        <property name="slot18" value="" />
        <property name="slot19" value="" />
        <property name="slot20" value="" />
      </properties>
      <layout>
        <posX>435</posX>
        <posY>49</posY>
      </layout>
    </component>
    <component id="EventVisualizer.1" type_id="asterics.EventVisualizer">
      <description>Simple Event Visualizer</description>
      <ports />
      <properties>
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>533</posX>
        <posY>47</posY>
      </layout>
      <gui>
        <posX>50</posX>
        <posY>4207</posY>
        <width>2604</width>
        <height>741</height>
      </gui>
    </component>
    <component id="TextArea.1" type_id="asterics.TextArea">
      <description>GUI component, which displays text.</description>
      <ports>
        <inputPort portTypeID="setText" sync="false">
          <properties />
        </inputPort>
        <inputPort portTypeID="appendText" sync="false">
          <properties />
        </inputPort>
        <outputPort portTypeID="text">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="caption" value="Text Display" />
        <property name="default" value="Install and start openhab, and use the demo package during first time startup (https://www.openhab.org/docs/configuration/packages.html#demo-package-sample-setup); Then open the basic UI of the Kitchen: http://localhost/basicui/app?w=GF_Kitchen&amp;sitemap=demo" />
        <property name="editable" value="false" />
        <property name="fontSize" value="14" />
        <property name="textColor" value="0" />
        <property name="backgroundColor" value="11" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>19</posX>
        <posY>42</posY>
      </layout>
      <gui>
        <posX>2562</posX>
        <posY>2111</posY>
        <width>2604</width>
        <height>1112</height>
      </gui>
    </component>
    <component id="Slider.1" type_id="asterics.Slider">
      <description>a slider GUI element which provides the slider value at an output port</description>
      <ports>
        <inputPort portTypeID="setValue" sync="false">
          <properties />
        </inputPort>
        <inputPort portTypeID="in" sync="false">
          <properties />
        </inputPort>
        <outputPort portTypeID="value">
          <properties />
        </outputPort>
        <outputPort portTypeID="out">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="min" value="0" />
        <property name="max" value="100" />
        <property name="default" value="50" />
        <property name="gain" value="0.01" />
        <property name="autosend" value="true" />
        <property name="caption" value="Item Temperature_GF_Kitchen" />
        <property name="majorTickSpacing" value="20" />
        <property name="minorTickSpacing" value="5" />
        <property name="alignment" value="0" />
        <property name="fontSize" value="14" />
        <property name="storeValue" value="false" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>122</posX>
        <posY>43</posY>
      </layout>
      <gui>
        <posX>50</posX>
        <posY>3281</posY>
        <width>2604</width>
        <height>926</height>
      </gui>
    </component>
    <component id="Mouse.1" type_id="asterics.Mouse">
      <description>Local mouse actuator, emulates mouse activity on local system</description>
      <ports>
        <inputPort portTypeID="mouseX">
          <properties />
        </inputPort>
        <inputPort portTypeID="mouseY">
          <properties />
        </inputPort>
        <inputPort portTypeID="action">
          <properties />
        </inputPort>
        <outputPort portTypeID="outX">
          <properties />
        </outputPort>
        <outputPort portTypeID="outY">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="enableMouse" value="True" />
        <property name="absolutePosition" value="False" />
        <property name="startCentered" value="true" />
        <property name="xMin" value="0" />
        <property name="xMax" value="0" />
        <property name="yMin" value="0" />
        <property name="yMax" value="0" />
      </properties>
      <layout>
        <posX>425</posX>
        <posY>194</posY>
      </layout>
    </component>
    <component id="MathEvaluator.1" type_id="asterics.MathEvaluator">
      <description>Mathematical expression evaluator</description>
      <ports>
        <inputPort portTypeID="inA">
          <properties />
        </inputPort>
        <inputPort portTypeID="inB">
          <properties />
        </inputPort>
        <inputPort portTypeID="inC">
          <properties />
        </inputPort>
        <inputPort portTypeID="inD">
          <properties />
        </inputPort>
        <outputPort portTypeID="out">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="expression" value="a*(b/50)" />
      </properties>
      <layout>
        <posX>221</posX>
        <posY>189</posY>
      </layout>
    </component>
    <component id="Slider.1.2" type_id="asterics.Slider">
      <description>a slider GUI element which provides the slider value at an output port</description>
      <ports>
        <inputPort portTypeID="setValue">
          <properties />
        </inputPort>
        <inputPort portTypeID="in">
          <properties />
        </inputPort>
        <outputPort portTypeID="value">
          <properties />
        </outputPort>
        <outputPort portTypeID="out">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="min" value="0" />
        <property name="max" value="100" />
        <property name="default" value="50" />
        <property name="gain" value="0.01" />
        <property name="autosend" value="true" />
        <property name="caption" value="mouse speed" />
        <property name="majorTickSpacing" value="10" />
        <property name="minorTickSpacing" value="5" />
        <property name="alignment" value="0" />
        <property name="fontSize" value="14" />
        <property name="storeValue" value="false" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>216</posX>
        <posY>348</posY>
      </layout>
      <gui>
        <posX>4188</posX>
        <posY>222</posY>
        <width>2788</width>
        <height>733</height>
      </gui>
    </component>
    <component id="ButtonGrid.1.1" type_id="asterics.ButtonGrid">
      <description>Keyboard which sends event after button press</description>
      <ports />
      <properties>
        <property name="caption" value="" />
        <property name="horizontalOrientation" value="True" />
        <property name="textColor" value="13" />
        <property name="backgroundColor" value="13" />
        <property name="borderColor" value="13" />
        <property name="borderThickness" value="2" />
        <property name="selectionFrameColor" value="13" />
        <property name="selectionFrameThickness" value="4" />
        <property name="displayGUI" value="true" />
        <property name="buttonCaption1" value="start/stop" />
        <property name="buttonCaption2" value="Drag click" />
        <property name="buttonCaption3" value="Right Click" />
        <property name="buttonCaption4" value="Double Click" />
        <property name="buttonCaption5" value="" />
        <property name="buttonCaption6" value="" />
        <property name="buttonCaption7" value="" />
        <property name="buttonCaption8" value="" />
        <property name="buttonCaption9" value="" />
        <property name="buttonCaption10" value="" />
        <property name="buttonCaption11" value="" />
        <property name="buttonCaption12" value="" />
        <property name="buttonCaption13" value="" />
        <property name="buttonCaption14" value="" />
        <property name="buttonCaption15" value="" />
        <property name="buttonCaption16" value="" />
        <property name="buttonCaption17" value="" />
        <property name="buttonCaption18" value="" />
        <property name="buttonCaption19" value="" />
        <property name="buttonCaption20" value="" />
        <property name="toolTip1" value="" />
        <property name="toolTip2" value="" />
        <property name="toolTip3" value="" />
        <property name="toolTip4" value="" />
        <property name="toolTip5" value="" />
        <property name="toolTip6" value="" />
        <property name="toolTip7" value="" />
        <property name="toolTip8" value="" />
        <property name="toolTip9" value="" />
        <property name="toolTip10" value="" />
        <property name="toolTip11" value="" />
        <property name="toolTip12" value="" />
        <property name="toolTip13" value="" />
        <property name="toolTip14" value="" />
        <property name="toolTip15" value="" />
        <property name="toolTip16" value="" />
        <property name="toolTip17" value="" />
        <property name="toolTip18" value="" />
        <property name="toolTip19" value="" />
        <property name="toolTip20" value="" />
      </properties>
      <layout>
        <posX>216</posX>
        <posY>497</posY>
      </layout>
      <gui>
        <posX>62</posX>
        <posY>222</posY>
        <width>4112</width>
        <height>733</height>
      </gui>
    </component>
    <component id="StringDispatcher.1.1" type_id="asterics.StringDispatcher">
      <description>Send test from chosen slot</description>
      <ports>
        <inputPort portTypeID="slotDispatch">
          <properties />
        </inputPort>
        <outputPort portTypeID="output">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="delay" value="300" />
        <property name="slot1" value="@MOUSE:action,toggle" />
        <property name="slot2" value="@MOUSE:nextclick,drag" />
        <property name="slot3" value="@MOUSE:nextclick,right" />
        <property name="slot4" value="@MOUSE:nextclick,double" />
        <property name="slot5" value="" />
        <property name="slot6" value="" />
        <property name="slot7" value="" />
        <property name="slot8" value="" />
        <property name="slot9" value="" />
        <property name="slot10" value="" />
        <property name="slot11" value="" />
        <property name="slot12" value="" />
        <property name="slot13" value="" />
        <property name="slot14" value="" />
        <property name="slot15" value="" />
        <property name="slot16" value="" />
        <property name="slot17" value="" />
        <property name="slot18" value="" />
        <property name="slot19" value="" />
        <property name="slot20" value="" />
      </properties>
      <layout>
        <posX>314</posX>
        <posY>496</posY>
      </layout>
    </component>
    <component id="Deadzone.1" type_id="asterics.Deadzone">
      <description>Defines active/passive Zone for x/y values</description>
      <ports>
        <inputPort portTypeID="inX">
          <properties />
        </inputPort>
        <inputPort portTypeID="inY">
          <properties />
        </inputPort>
        <inputPort portTypeID="radius">
          <properties />
        </inputPort>
        <outputPort portTypeID="outX">
          <properties />
        </outputPort>
        <outputPort portTypeID="outY">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="xCenter" value="0" />
        <property name="yCenter" value="0" />
        <property name="radius" value="2" />
        <property name="mode" value="0" />
      </properties>
      <layout>
        <posX>331</posX>
        <posY>348</posY>
      </layout>
    </component>
    <component id="Timer.1" type_id="asterics.Timer">
      <description>measures and outputs time in milliseconds and fires events (periodically or once)</description>
      <ports>
        <inputPort portTypeID="period">
          <properties />
        </inputPort>
        <outputPort portTypeID="time">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="mode" value="0" />
        <property name="repeatCounter" value="1" />
        <property name="timePeriod" value="1000" />
        <property name="resolution" value="50" />
        <property name="waitPeriod" value="0" />
        <property name="autostart" value="false" />
      </properties>
      <layout>
        <posX>425</posX>
        <posY>352</posY>
      </layout>
    </component>
    <component id="WavefilePlayer.1" type_id="asterics.WavefilePlayer">
      <description>Simple SAPI component. It uses default system voice settings. </description>
      <ports>
        <inputPort portTypeID="wavefileName">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="filename" value="data\sounds\2.wav" />
      </properties>
      <layout>
        <posX>537</posX>
        <posY>196</posY>
      </layout>
    </component>
    <component id="BarDisplay.2" type_id="asterics.BarDisplay">
      <description>Bar-display</description>
      <ports>
        <inputPort portTypeID="input">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="displayBuffer" value="0" />
        <property name="min" value="0" />
        <property name="max" value="1000" />
        <property name="threshold" value="500" />
        <property name="displayThreshold" value="false" />
        <property name="integerDisplay" value="false" />
        <property name="mode" value="1" />
        <property name="gridColor" value="0" />
        <property name="barColor" value="8" />
        <property name="backgroundColor" value="11" />
        <property name="fontSize" value="14" />
        <property name="caption" value="click" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>527</posX>
        <posY>350</posY>
      </layout>
      <gui>
        <posX>6312</posX>
        <posY>889</posY>
        <width>675</width>
        <height>733</height>
      </gui>
    </component>
    <component id="OskaExternalScanning2D.1" type_id="OskaExternalScanning2D">
      <description>Component communicating with OSKA</description>
      <ports>
        <inputPort portTypeID="posColumn">
          <properties />
        </inputPort>
        <inputPort portTypeID="posRow">
          <properties />
        </inputPort>
        <outputPort portTypeID="action">
          <properties />
        </outputPort>
        <outputPort portTypeID="keycodes">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="port" value="4546" />
        <property name="title" value="OSKA keyboard" />
        <property name="oskaPath" value="..\oska\start keyboard.exe" />
        <property name="keyboardPath" value="keyboards\default.xml" />
        <property name="highlightStyle" value="0" />
        <property name="highlightResetPosition" value="0" />
        <property name="settingsFile" value="settings\default.kst" />
        <property name="windowDecorated" value="true" />
        <property name="eventScanningEnabled" value="true" />
        <property name="valueScanningEnabled" value="true" />
        <property name="inputRange" value="0" />
        <property name="resizeEnabled" value="false" />
      </properties>
      <layout>
        <posX>17</posX>
        <posY>489</posY>
      </layout>
      <gui>
        <posX>4875</posX>
        <posY>6889</posY>
        <width>5188</width>
        <height>3444</height>
      </gui>
    </component>
    <component id="ButtonGrid.2" type_id="asterics.ButtonGrid">
      <description>Keyboard which sends event after button press</description>
      <ports />
      <properties>
        <property name="caption" value="Camera Setup" />
        <property name="horizontalOrientation" value="True" />
        <property name="textColor" value="13" />
        <property name="backgroundColor" value="13" />
        <property name="borderColor" value="13" />
        <property name="borderThickness" value="2" />
        <property name="selectionFrameColor" value="13" />
        <property name="selectionFrameThickness" value="4" />
        <property name="displayGUI" value="true" />
        <property name="buttonCaption1" value="reset cam" />
        <property name="buttonCaption2" value="" />
        <property name="buttonCaption3" value="" />
        <property name="buttonCaption4" value="" />
        <property name="buttonCaption5" value="" />
        <property name="buttonCaption6" value="" />
        <property name="buttonCaption7" value="" />
        <property name="buttonCaption8" value="" />
        <property name="buttonCaption9" value="" />
        <property name="buttonCaption10" value="" />
        <property name="buttonCaption11" value="" />
        <property name="buttonCaption12" value="" />
        <property name="buttonCaption13" value="" />
        <property name="buttonCaption14" value="" />
        <property name="buttonCaption15" value="" />
        <property name="buttonCaption16" value="" />
        <property name="buttonCaption17" value="" />
        <property name="buttonCaption18" value="" />
        <property name="buttonCaption19" value="" />
        <property name="buttonCaption20" value="" />
        <property name="toolTip1" value="" />
        <property name="toolTip2" value="" />
        <property name="toolTip3" value="" />
        <property name="toolTip4" value="" />
        <property name="toolTip5" value="" />
        <property name="toolTip6" value="" />
        <property name="toolTip7" value="" />
        <property name="toolTip8" value="" />
        <property name="toolTip9" value="" />
        <property name="toolTip10" value="" />
        <property name="toolTip11" value="" />
        <property name="toolTip12" value="" />
        <property name="toolTip13" value="" />
        <property name="toolTip14" value="" />
        <property name="toolTip15" value="" />
        <property name="toolTip16" value="" />
        <property name="toolTip17" value="" />
        <property name="toolTip18" value="" />
        <property name="toolTip19" value="" />
        <property name="toolTip20" value="" />
      </properties>
      <layout>
        <posX>16</posX>
        <posY>343</posY>
      </layout>
      <gui>
        <posX>62</posX>
        <posY>889</posY>
        <width>4112</width>
        <height>733</height>
      </gui>
    </component>
    <component id="MathEvaluator.2" type_id="asterics.MathEvaluator">
      <description>Mathematical expression evaluator</description>
      <ports>
        <inputPort portTypeID="inA">
          <properties />
        </inputPort>
        <inputPort portTypeID="inB">
          <properties />
        </inputPort>
        <inputPort portTypeID="inC">
          <properties />
        </inputPort>
        <inputPort portTypeID="inD">
          <properties />
        </inputPort>
        <outputPort portTypeID="out">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="expression" value="a*(b/50)" />
      </properties>
      <layout>
        <posX>323</posX>
        <posY>192</posY>
      </layout>
    </component>
    <component id="Slider.1.1" type_id="asterics.Slider">
      <description>a slider GUI element which provides the slider value at an output port</description>
      <ports>
        <inputPort portTypeID="setValue">
          <properties />
        </inputPort>
        <inputPort portTypeID="in">
          <properties />
        </inputPort>
        <outputPort portTypeID="value">
          <properties />
        </outputPort>
        <outputPort portTypeID="out">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="min" value="0" />
        <property name="max" value="100" />
        <property name="default" value="20" />
        <property name="gain" value="0.01" />
        <property name="autosend" value="True" />
        <property name="caption" value="click time" />
        <property name="majorTickSpacing" value="20" />
        <property name="minorTickSpacing" value="5" />
        <property name="alignment" value="0" />
        <property name="fontSize" value="14" />
        <property name="storeValue" value="false" />
        <property name="displayGUI" value="true" />
      </properties>
      <layout>
        <posX>417</posX>
        <posY>501</posY>
      </layout>
      <gui>
        <posX>4188</posX>
        <posY>889</posY>
        <width>2112</width>
        <height>733</height>
      </gui>
    </component>
    <component id="MathEvaluator.3" type_id="asterics.MathEvaluator">
      <description>Mathematical expression evaluator</description>
      <ports>
        <inputPort portTypeID="inA">
          <properties />
        </inputPort>
        <inputPort portTypeID="inB">
          <properties />
        </inputPort>
        <inputPort portTypeID="inC">
          <properties />
        </inputPort>
        <inputPort portTypeID="inD">
          <properties />
        </inputPort>
        <outputPort portTypeID="out">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="expression" value="a*20+100" />
      </properties>
      <layout>
        <posX>515</posX>
        <posY>502</posY>
      </layout>
    </component>
    <component id="Averager.1" type_id="asterics.Averager">
      <description>Linked list-based averager or accumulator</description>
      <ports>
        <inputPort portTypeID="input">
          <properties />
        </inputPort>
        <outputPort portTypeID="output">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="enabled" value="true" />
        <property name="bufferSize" value="5" />
        <property name="mode" value="0" />
        <property name="autoReenableTime" value="0" />
      </properties>
      <layout>
        <posX>120</posX>
        <posY>188</posY>
      </layout>
    </component>
    <component id="Averager.1.1" type_id="asterics.Averager">
      <description>Linked list-based averager or accumulator</description>
      <ports>
        <inputPort portTypeID="input">
          <properties />
        </inputPort>
        <outputPort portTypeID="output">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="enabled" value="true" />
        <property name="bufferSize" value="5" />
        <property name="mode" value="0" />
        <property name="autoReenableTime" value="0" />
      </properties>
      <layout>
        <posX>110</posX>
        <posY>346</posY>
      </layout>
    </component>
    <component id="modelSwitcher.1" type_id="asterics.modelSwitcher">
      <description>The ModelSwitcher plugin can be used to deploy and start a model via incoming event or model name</description>
      <ports>
        <inputPort portTypeID="modelName">
          <properties />
        </inputPort>
      </ports>
      <properties>
        <property name="model" value="demomenu.acs" />
      </properties>
      <layout>
        <posX>114</posX>
        <posY>489</posY>
      </layout>
    </component>
    <component id="XFacetrackerLK.1" type_id="asterics.XFacetrackerLK">
      <description>X-platform webcamera-based face tracking sensor</description>
      <ports>
        <outputPort portTypeID="noseX">
          <properties />
        </outputPort>
        <outputPort portTypeID="noseY">
          <properties />
        </outputPort>
        <outputPort portTypeID="chinX">
          <properties />
        </outputPort>
        <outputPort portTypeID="chinY">
          <properties />
        </outputPort>
      </ports>
      <properties>
        <property name="frameGrabber" value="Default" />
        <property name="frameGrabberFormat" value="" />
        <property name="deviceList" value="" />
        <property name="cameraSelection" value="0" />
        <property name="cameraResolution" value="1" />
        <property name="frameRate" value="0" />
        <property name="titleVideoFrameWindow" value="" />
        <property name="displayGUI" value="true" />
        <property name="enableOverlaySettings" value="true" />
      </properties>
      <layout>
        <posX>17</posX>
        <posY>186</posY>
      </layout>
      <gui>
        <posX>7375</posX>
        <posY>444</posY>
        <width>2000</width>
        <height>1500</height>
      </gui>
    </component>
  </components>
  <channels>
    <channel id="outputATStringDispatcher.1_TO_actionStringATopenHAB.1_c">
      <source>
        <component id="StringDispatcher.1" />
        <port id="output" />
      </source>
      <target>
        <component id="openHAB.1_c" />
        <port id="actionString" />
      </target>
    </channel>
    <channel id="valueATSlider.1_TO_item1inATopenHAB.1_c">
      <source>
        <component id="Slider.1" />
        <port id="value" />
      </source>
      <target>
        <component id="openHAB.1_c" />
        <port id="item1in" />
      </target>
    </channel>
    <channel id="item1ATopenHAB.1_c_TO_setValueATSlider.1">
      <source>
        <component id="openHAB.1_c" />
        <port id="item1" />
      </source>
      <target>
        <component id="Slider.1" />
        <port id="setValue" />
      </target>
    </channel>
    <channel id="binding.3">
      <description />
      <source>
        <component id="Averager.1" />
        <port id="output" />
      </source>
      <target>
        <component id="MathEvaluator.1" />
        <port id="inA" />
      </target>
    </channel>
    <channel id="binding.4">
      <description />
      <source>
        <component id="Averager.1.1" />
        <port id="output" />
      </source>
      <target>
        <component id="MathEvaluator.2" />
        <port id="inA" />
      </target>
    </channel>
    <channel id="binding.5">
      <description />
      <source>
        <component id="Slider.1.2" />
        <port id="value" />
      </source>
      <target>
        <component id="MathEvaluator.1" />
        <port id="inB" />
      </target>
    </channel>
    <channel id="binding.6">
      <description />
      <source>
        <component id="StringDispatcher.1.1" />
        <port id="output" />
      </source>
      <target>
        <component id="Mouse.1" />
        <port id="action" />
      </target>
    </channel>
    <channel id="binding.7">
      <description />
      <source>
        <component id="Averager.1" />
        <port id="output" />
      </source>
      <target>
        <component id="Deadzone.1" />
        <port id="inX" />
      </target>
    </channel>
    <channel id="binding.8">
      <description />
      <source>
        <component id="Averager.1.1" />
        <port id="output" />
      </source>
      <target>
        <component id="Deadzone.1" />
        <port id="inY" />
      </target>
    </channel>
    <channel id="binding.9">
      <description />
      <source>
        <component id="Timer.1" />
        <port id="time" />
      </source>
      <target>
        <component id="BarDisplay.2" />
        <port id="input" />
      </target>
    </channel>
    <channel id="binding.10">
      <description />
      <source>
        <component id="Slider.1.2" />
        <port id="value" />
      </source>
      <target>
        <component id="MathEvaluator.2" />
        <port id="inB" />
      </target>
    </channel>
    <channel id="binding.11">
      <description />
      <source>
        <component id="MathEvaluator.2" />
        <port id="out" />
      </source>
      <target>
        <component id="Mouse.1" />
        <port id="mouseY" />
      </target>
    </channel>
    <channel id="binding.12">
      <description />
      <source>
        <component id="Slider.1.1" />
        <port id="value" />
      </source>
      <target>
        <component id="MathEvaluator.3" />
        <port id="inA" />
      </target>
    </channel>
    <channel id="binding.13">
      <description />
      <source>
        <component id="MathEvaluator.3" />
        <port id="out" />
      </source>
      <target>
        <component id="Timer.1" />
        <port id="period" />
      </target>
    </channel>
    <channel id="binding.14">
      <description />
      <source>
        <component id="XFacetrackerLK.1" />
        <port id="noseX" />
      </source>
      <target>
        <component id="Averager.1" />
        <port id="input" />
      </target>
    </channel>
    <channel id="binding.15">
      <description />
      <source>
        <component id="XFacetrackerLK.1" />
        <port id="noseY" />
      </source>
      <target>
        <component id="Averager.1.1" />
        <port id="input" />
      </target>
    </channel>
    <channel id="binding.16">
      <description />
      <source>
        <component id="MathEvaluator.1" />
        <port id="out" />
      </source>
      <target>
        <component id="Mouse.1" />
        <port id="mouseX" />
      </target>
    </channel>
  </channels>
  <eventChannels>
    <eventChannel id="button1_dispatchSlot1">
      <sources>
        <source>
          <component id="ButtonGrid.1" />
          <eventPort id="button1" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1" />
          <eventPort id="dispatchSlot1" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="button2_dispatchSlot2">
      <sources>
        <source>
          <component id="ButtonGrid.1" />
          <eventPort id="button2" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1" />
          <eventPort id="dispatchSlot2" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="button3_dispatchSlot3">
      <sources>
        <source>
          <component id="ButtonGrid.1" />
          <eventPort id="button3" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1" />
          <eventPort id="dispatchSlot3" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="button4_dispatchSlot4">
      <sources>
        <source>
          <component id="ButtonGrid.1" />
          <eventPort id="button4" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1" />
          <eventPort id="dispatchSlot4" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="item1changed_eventDisplay">
      <sources>
        <source>
          <component id="openHAB.1_c" />
          <eventPort id="item1changed" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="EventVisualizer.1" />
          <eventPort id="eventDisplay" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="item2changed_eventDisplay">
      <sources>
        <source>
          <component id="openHAB.1_c" />
          <eventPort id="item2changed" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="EventVisualizer.1" />
          <eventPort id="eventDisplay" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="item3changed_eventDisplay">
      <sources>
        <source>
          <component id="openHAB.1_c" />
          <eventPort id="item3changed" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="EventVisualizer.1" />
          <eventPort id="eventDisplay" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="button1_dispatchSlot1">
      <description />
      <sources>
        <source>
          <component id="ButtonGrid.1.1" />
          <eventPort id="button1" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1.1" />
          <eventPort id="dispatchSlot1" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="button2_dispatchSlot2">
      <description />
      <sources>
        <source>
          <component id="ButtonGrid.1.1" />
          <eventPort id="button2" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1.1" />
          <eventPort id="dispatchSlot2" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="button3_dispatchSlot3">
      <description />
      <sources>
        <source>
          <component id="ButtonGrid.1.1" />
          <eventPort id="button3" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1.1" />
          <eventPort id="dispatchSlot3" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="button4_dispatchSlot4">
      <description />
      <sources>
        <source>
          <component id="ButtonGrid.1.1" />
          <eventPort id="button4" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="StringDispatcher.1.1" />
          <eventPort id="dispatchSlot4" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="enterZone_start">
      <description />
      <sources>
        <source>
          <component id="Deadzone.1" />
          <eventPort id="enterZone" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="Timer.1" />
          <eventPort id="start" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="exitZone_stop">
      <description />
      <sources>
        <source>
          <component id="Deadzone.1" />
          <eventPort id="exitZone" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="Timer.1" />
          <eventPort id="stop" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="exitZone_reset">
      <description />
      <sources>
        <source>
          <component id="Deadzone.1" />
          <eventPort id="exitZone" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="Timer.1" />
          <eventPort id="reset" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="periodFinished_Start">
      <description />
      <sources>
        <source>
          <component id="Timer.1" />
          <eventPort id="periodFinished" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="WavefilePlayer.1" />
          <eventPort id="Start" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="eventOut1_switchModel">
      <description />
      <sources>
        <source>
          <component id="OskaExternalScanning2D.1" />
          <eventPort id="eventOut1" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="modelSwitcher.1" />
          <eventPort id="switchModel" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="periodFinished_leftClick">
      <description />
      <sources>
        <source>
          <component id="Timer.1" />
          <eventPort id="periodFinished" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="Mouse.1" />
          <eventPort id="leftClick" />
        </target>
      </targets>
    </eventChannel>
    <eventChannel id="button1_init">
      <description />
      <sources>
        <source>
          <component id="ButtonGrid.2" />
          <eventPort id="button1" />
        </source>
      </sources>
      <targets>
        <target>
          <component id="XFacetrackerLK.1" />
          <eventPort id="init" />
        </target>
      </targets>
    </eventChannel>
  </eventChannels>
  <modelGUI>
    <Decoration>true</Decoration>
    <Fullscreen>false</Fullscreen>
    <AlwaysOnTop>false</AlwaysOnTop>
    <ToSystemTray>false</ToSystemTray>
    <ShopControlPanel>true</ShopControlPanel>
    <AREGUIWindow>
      <posX>-50</posX>
      <posY>200</posY>
      <width>7312</width>
      <height>1889</height>
    </AREGUIWindow>
  </modelGUI>
</model>